(part "SK34SMA-3G"
    (packageRef "DIOM5027X240N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Diotec")
    (property "Manufacturer_Part_Number" "SK34SMA-3G")
    (property "Mouser_Part_Number" "637-SK34SMA-3G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diotec-Semiconductor/SK34SMA-3G?qs=OlC7AqGiEDkrZWGTiN%2FPpg%3D%3D")
    (property "Arrow_Part_Number" "SK34SMA-3G")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/sk34sma-3g/diotec-semiconductor-ag?region=europe")
    (property "Description" "Schottky Diodes & Rectifiers Schottky Diode, SMA, 40V, 3A")
    (property "Datasheet_Link" "https://diotec.com/request/datasheet/sk34sma-3g.pdf")
    (property "symbolName1" "SK34SMA-3G")
)
