(part "IRLZ44NPBF"
    (packageRef "TO254P469X1042X1967-3P")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INPUT))
        (port "2" (symbPinId 2) (portName "D") (portType OUTPUT))
        (port "3" (symbPinId 3) (portName "S") (portType INPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IRLZ44NPBF")
    (property "Mouser_Part_Number" "942-IRLZ44NPBF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/IRLZ44NPBF?qs=9%252BKlkBgLFf15OZZk%252BD0ibg%3D%3D")
    (property "Arrow_Part_Number" "IRLZ44NPBF")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/irlz44npbf/infineon-technologies-ag?utm_currency=USD&region=europe")
    (property "Description" "N-channel MOSFET,IRLZ44N 47A 55V")
    (property "Datasheet_Link" "http://www.irf.com/product-info/datasheets/data/irlz44n.pdf")
    (property "symbolName1" "IRLZ44NPBF")
)
