M48
; DRILL file {KiCad 9.0.7} date 2026-03-21T02:29:28+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-21T02:29:28+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X84.74Y-181.74
X117.76Y-233.81
X133.0Y-183.01
T2
X53.8Y-44.0
X54.0Y-235.9
X261.1Y-44.0
X261.1Y-235.9
M30
