(part "ACPL-C87B-000E"
    (packageRef "SOIC127P1150X331-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SDHN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VOUT-") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VOUT+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "630-ACPL-C87B-000E")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Broadcom-Avago/ACPL-C87B-000E?qs=mhB89zxvawmLiWfngQW5pg%3D%3D")
    (property "Manufacturer_Name" "Avago Technologies")
    (property "Manufacturer_Part_Number" "ACPL-C87B-000E")
    (property "Description" "Optically isolated voltage sensor,SSO8 Broadcom ACPL-C87B-000E, Isolation Amplifier, 4.5  5.5 V, 8-Pin SSO")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/ACPL-C87B-000E.pdf")
    (property "symbolName1" "ACPL-C87B-000E")
)
