(part "AGC0603X7R250-105KXP"
    (packageRef "CAPC1608X95N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "Venkel")
    (property "Manufacturer_Part_Number" "AGC0603X7R250-105KXP")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "1 F +/-10% 25V Ceramic Capacitor X7R 0603 (1608 Metric)")
    (property "Datasheet_Link" "https://g.componentsearchengine.com/Datasheets/0/20899965.pdf")
    (property "symbolName1" "AGC0603X7R250-105KXP")
)
