(part "HCPL-2211-300E"
    (packageRef "6N137")
    (interface
        (port "1" (symbPinId 1) (portName "NC_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ANODE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CATHODE") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VO") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Avago Technologies")
    (property "Manufacturer_Part_Number" "HCPL-2211-300E")
    (property "Mouser_Part_Number" "630-HCPL-2211-300E")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Broadcom-Avago/HCPL-2211-300E?qs=xnajaXqBF9%252BPSYdymxWXoA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Broadcom, HCPL-2211-300E DC Input Logic Gate Output Optocoupler, Surface Mount, 8-Pin DIP")
    (property "Datasheet_Link" "https://docs.broadcom.com/doc/Very-High-CMR-Wide-VCC-Logic-Gate-Optocouplers-DS")
    (property "symbolName1" "HCPL-2211-300E")
)
