(part "ATB107M035"
    (packageRef "CAPAE660X800N")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "Cornell Dubilier")
    (property "Manufacturer_Part_Number" "ATB107M035")
    (property "Mouser_Part_Number" "598-ATB107M035")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Cornell-Dubilier-CDE/ATB107M035?qs=lc2O%252BfHJPVYF0CZ2fG%252BHrg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Aluminum Electrolytic Capacitors - SMD 35VDC 100uF 20% 420mA a. 120Hz")
    (property "Datasheet_Link" "https://www.cde.com/resources/catalogs/ATB.pdf")
    (property "symbolName1" "ATB107M035")
)
